definitions:
  image-optimization-api_internal_service_image.GetImageResponse:
    properties:
      image:
        $ref: '#/definitions/image-optimization-api_internal_service_image.Info'
    type: object
  image-optimization-api_internal_service_image.Info:
    properties:
      key:
        type: string
      url:
        type: string
    type: object
  image-optimization-api_internal_service_image.ListImageResponse:
    properties:
      images:
        items:
          $ref: '#/definitions/image-optimization-api_internal_service_image.Info'
        type: array
    type: object
  image-optimization-api_internal_service_image.ListOriginImageResponse:
    properties:
      keys:
        items:
          type: string
        type: array
    type: object
  image-optimization-api_pkg_server.EmptyResponse:
    type: object
info:
  contact: {}
paths:
  /api/image:
    post:
      description: Uploads an image
      operationId: upload-image
      parameters:
      - description: Images to upload
        in: formData
        name: images
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/image-optimization-api_pkg_server.EmptyResponse'
      tags:
      - Images
  /api/image/{image_id}:
    get:
      description: Retrieves an image by ID
      operationId: get-image
      parameters:
      - description: Image ID
        in: path
        name: image_id
        required: true
        type: string
      - description: 'Compression Quality (one of: 100, 75, 50, 25)'
        in: query
        name: quality
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/image-optimization-api_internal_service_image.GetImageResponse'
      tags:
      - Images
  /api/image/list:
    get:
      description: Retrieves a list of images
      operationId: list-images
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/image-optimization-api_internal_service_image.ListImageResponse'
      tags:
      - Images
  /api/image/origin:
    get:
      description: Retrieves a list of original images, excluding those with compression
        quality suffixes
      operationId: list-origin-images
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/image-optimization-api_internal_service_image.ListOriginImageResponse'
      tags:
      - Images
swagger: "2.0"
